# Generated by Django 3.1.2 on 2020-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Gokul H', max_length=255),
        ),
    ]
