# Generated by Django 3.1.2 on 2020-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20201009_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='NO SNIPPET AVAILABLE', max_length=255),
        ),
    ]
